### ISSUE TITLE
Why does spec ask routing via hashes?

### ISSUE THREAD

**Issue by gaearon** [TodoFlux/todoflux#4]
Any specific reasons routing should be done with hashes instead of pushState?

**Comment by pukhalski** [comment]
If it's possible I personally see the value of using hashes without any server support in ability to restore the app state and don't get 404 wherever it happens. Unfortunately, we didn't plan to have isomorphic or universal apps right away, since it requires a lot of effort to invest into the infrastructure.

Does it make any sense?

**Comment by gaearon** [comment]
I still think `pushState`-style routes are better because:
1. You can have a catch-all path on server—no need to get universal to support nice paths.
2. Gradually you can teach your server to preload JSON by looking at URL and embed JSON into the HTML response, so that, even though the app isn't universal, at least it can show data instantly.
3. The migration path to universal app will be easier.

**Comment by kirjs** [comment]
Definitely :+1: on pushState, but is there a way to make it work with gh-pages?

**Comment by pukhalski** [comment]
I personally agree with everything above.

But considering current circumstances — we use `gh-pages`, it could bring some bad UX for the end users. We can still have `pushState`-enabled apps, but we are not ready to provide server-side fallback for that. 

Is that possible to make the example work through the hash-powered urls, and mark how to turn `pushState` on under `Implementation` section in the app `readme.md` file?

**Comment by gaearon** [comment]
I totally forgot hosting on GH pages is a requirement.
In this case, it makes sense.

**Comment by pukhalski** [comment]
Sorry for that, mate. We are still stuck with TodoMVC infrastructure...
